import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { AddEditModalProvider } from "@/context/AddEditModalContext";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { NotificationProvider } from "@/context/NotificationContext";
import { TriggerProvider } from "@/context/TriggerContext";
import { UserProvider } from "@/context/UserContext";

const font = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Inventory app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <UserProvider>
          <TriggerProvider>
            <NotificationProvider>
              <EdgeStoreProvider>
                <AddEditModalProvider>{children}</AddEditModalProvider>
              </EdgeStoreProvider>
            </NotificationProvider>
          </TriggerProvider>
        </UserProvider>
      </body>
    </html>
  );
}
